[package]
name = "frisket"
version = "0.1.0"
edition = "2024"
authors = ["Jan Philipp Thiele"]
description = "A CLI tool for managing LaTeX projects"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"]}
dialoguer = "0.12.0"
indoc = "2.0.7"
serde = { version = "1.0.228", features = ["alloc", "derive", "rc"] }
toml = "0.9.10"
